# Generated by Django 6.0.4 on 2026-04-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_participant_feedback_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='payment_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='transaction_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='transactions/'),
        ),
    ]
