# Generated by Django 6.0.4 on 2026-04-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='feedback_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
